### ISSUE TITLE
return the mask of sampled pixels

### ISSUE THREAD

**Issue by navid-mahmoudian** [ulikk/panoviewer#1]
Hi,

First of all, thanks a lot for this interesting code. How is it possible to add a feature to have the mask of sampled pixels at the same time of rendering? I mean along with the rendered view I want to have a mask image (of type unsigned byte and same size of the equirectangular image) which represents pixels which are sampled from the equirectangular images.

**Comment by ulikk** [comment]
Hello,

I am not sure if I understand your question correctly. The sampled pixels are projected into the equirectangular view using the spherical to cartesian coordinates, as shown in the pixel shader. 
I see basically two methods to achieve this
 * tesselate the view plane (using a regular triangle or quad mesh) and use forward warping to render the warped tesselation as mask on the equirectangular image (no custom shader needed, less accurate)
* invert the cartesian to spherical conversion and render a quad in the size of the equirectangular image and perform a "inside view" test in spherical coordinates in a custom fragment shader (needs custom shader, pixel accurate)

hope that helps,
greetings

**Comment by navid-mahmoudian** [comment]
Thank a lot for your response. Actually, I solved it using imageStore
function which I think it should be more efficient, because at the same
time that the fragment shader computes the sampled pixels coordinate, it
can write them to another texture image using imageStore. In case you are
interested, please refer to this answer:
https://stackoverflow.com/questions/53102909/how-to-return-the-mask-of-sampled-pixels

Regards,
Navid

**Comment by ulikk** [comment]
Hi, 
this basically conforms to the forward warping approach I described - but don't you get sampling errors (i.e. holes in your masked image) when the distance of two adjacent pixels in the view is larger than one in the equirectangular image?

Regards,
Ulrich

**Comment by navid-mahmoudian** [comment]
Hi again,
Yes, I get holes, especially when the viewport is around the poles, but
this is actually what I wanted. I wanted to find exactly the pixels which
are used from the equirectangular image. As it is mentioned in the
StackOverflow, since in the code linear filter is used
"glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR)", I
marked the nearest 4 texels in my mask. Am I missing something?

Regards,
Navid

**Comment by ulikk** [comment]
Hello,
Ah, in that case that works of course. I wrongly assumed you wanted to mask the whole area in the rectangular image that is covered by the view.
