### ISSUE TITLE
how to change the shader program to accept cube map

### ISSUE THREAD

**Issue by navid-mahmoudian** [ulikk/panoviewer#4]
Hi,
Thank you very much for this great code. I really like the idea that you have used kind of ray tracing technique to build the viewport (where you create "const Vec3d QuadWorld[4]" and only sending the 4 corners of the viewport plane to the vertex shader). I was wondering to ask if you know how we can change this program (again using this ray tracing technique) to use cube map instead of the equirectangular image?

**Comment by ulikk** [comment]
Hi, depending on the layout of your cube faces it should only be necessary to change the lines
```
   spherecoords.x = (atan(spherepos.y, -spherepos.x)+pi)/(2.0*pi);
   spherecoords.y = acos(spherepos.z)/(pi);"
```
from the shader to map the ray (the direction of the "spherepos" vector) to the according
cube face position on the texture, where "spherecoords" is the texture coordinate.
Which means:
- differentiate which cube face was hit using the spherepos vector
- intersect ray with this faces' plane
- map intersection to according area on the cube map

hope that helps,
kind regards
